### ISSUE TITLE
I want to use it in native HTML. How？

### ISSUE THREAD

**Issue by a1003584293** [theideasaler/angular-thumb-video#2]
I want to use it in native HTML. How？

**Comment by theideasaler** [comment]
Hi, this plugin is built for Angular and it wraps the native `<video>` inside it. If you want to use it with native HTML, then you will probably need to implement your own version. Regarding how to generate the thumbnail video, you can refer to this [utility](https://github.com/theideasaler/angular-thumb-video/blob/main/projects/ngx-thumbnail-video/src/lib/utils/ngx-preload-thumb.util.ts)
